[package]
name = "sky-cua-linux"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
ashpd.workspace = true
atspi.workspace = true
chrono.workspace = true
enumflags2.workspace = true
gstreamer.workspace = true
gstreamer-app.workspace = true
image.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
reis.workspace = true
sky-cua-input-helper = { path = "../sky-cua-input-helper" }
sky-cua-platform = { path = "../sky-cua-platform" }
tokio = { workspace = true, features = ["process"] }
tracing.workspace = true
webp.workspace = true
xkbcommon.workspace = true
zbus.workspace = true
url.workspace = true

[dev-dependencies]
serial_test = "3.2.0"
sky-cua-platform = { path = "../sky-cua-platform", features = ["test-support"] }
