import type { API_MANIFEST } from "./api.ts";

type Manifest = typeof API_MANIFEST;

export function generateDeclarations(manifest: Manifest): string {
  const blocks: string[] = [
    "// Generated by @heliasar/browser-use. Do not edit.",
    "",
  ];
  for (const [name, members] of Object.entries(manifest.interfaces)) {
    blocks.push(`export interface ${name} {`);
    for (const member of Object.values(members)) {
      for (const declaration of member.declarations) blocks.push(`  ${declaration.text}`);
    }
    blocks.push("}", "");
  }
  for (const { text } of Object.values(manifest.types)) {
    blocks.push(validTypeScript(text).replace(/^(type|interface) /u, "export $1 "), "");
  }
  blocks.push(
    "export type BrowserGlobals = typeof globalThis & { agent?: Agent; display?: (value: unknown) => Promise<void>; nodeRepl?: unknown };",
    "export type SetupBrowserRuntimeOptions = { globals: BrowserGlobals; elicitationDisplayName?: string };",
    "export declare function setupBrowserRuntime(options: SetupBrowserRuntimeOptions): Promise<void>;",
    "export declare const COMMANDS: readonly string[];",
    "export declare const API_SURFACE: Readonly<Record<string, readonly string[]>>;",
    "",
  );
  return blocks.join("\n");
}

function validTypeScript(text: string): string {
  return text
    .replace(
      "string | (arg: TArg) => TResult | Promise<TResult>",
      "string | ((arg: TArg) => TResult | Promise<TResult>)",
    )
    .replace(
      "string | (element: Element, arg: TArg) => TResult | Promise<TResult>",
      "string | ((element: Element, arg: TArg) => TResult | Promise<TResult>)",
    );
}
