pub(crate) mod actions;
pub mod app_policy;
pub mod apps;
pub mod atspi;
pub mod backend;
pub mod coords;
pub mod cosmic_helper;
pub mod doctor;
pub mod env_probe;
pub mod focus;
pub mod kwin;
pub mod portal;
pub mod session_env;
pub mod setup;
pub mod virtual_input;
pub mod windowing;
pub mod x11;

pub use backend::LinuxDesktopBackend;
